In [4]:
import numpy as np

np.__version__

'1.21.0'

In [6]:
john = [10,8,6,7]
x = np.array(john)

print(type(x))

<class 'numpy.ndarray'>


In [ ]:
# 리스트에 있는 모든 원소에 1씩 추가::for문 방식
john = [10,8,6,7]

x = []
for i in john:
    x.append(i+1)

x

[11, 9, 7, 8]

In [ ]:
# 리스트 내포 방식 (이 방법을 이용해보도록 하자 ***)
x = [c+1 for c in john]
x

[11, 9, 7, 8]

In [ ]:
# numpy array를 활용한 방식
john = np.array(john)
john

array([10,  8,  6,  7])

In [ ]:
john+1

array([11,  9,  7,  8])

# 다차원 배열

In [ ]:
score = [[1,2,3,4],
        [5,6,7,8]]
X = np.array(score)
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
X.shape

(2, 4)

In [ ]:
X.dtype

dtype('int32')

In [ ]:
y = np.array([1.,2.,3.,4.])
y.shape

(4,)

In [ ]:
type(y.shape)

tuple

In [ ]:
x = (4)
type(x)

int

In [ ]:
type((4,)),type((4))

(tuple, int)

In [ ]:
X = np.arange(9)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
X.shape

(9,)

In [ ]:
y = X.reshape(3,3)
y.shape

(3, 3)

In [ ]:
X.reshape(-1,3,3)  #-1을 넣게되면 나머지는 알아서 처리해달라는 뜻이다. 원소가 9개에 3x3이므로 1x3x3으로 자동세팅됨.

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
X = np.arange(0,16)
X = X.reshape(4,4)
X = X.reshape(2,4,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
X = np.array([1,2,3])
y = np.array([[1],[2],[3]])
X.shape, y.shape

((3,), (3, 1))

In [ ]:
y =  y.reshape(-1)
y

array([1, 2, 3])

In [ ]:
X = np.arange(0,16)
X = X.reshape(-1,4,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

# 슬라이싱, 인덱싱

In [46]:
X = np.array([[4,5,6],[8,9,0]])
X

array([[4, 5, 6],
       [8, 9, 0]])

### Fancy Indexing

In [47]:
X[0,[1,2]]

array([5, 6])

### Slicing

In [48]:
X[0,1:]

array([5, 6])

### Boolean Indexing

In [43]:
X = np.array([c for c in range(1,6)]) #[1,2,3,4,5]
idx = [False,True,False,True,False,]
X[idx]

array([2, 4])

In [ ]:
X = np.array([1,5,3,7,6])
X>6

array([False, False, False,  True, False])

In [ ]:
X[X>6]

array([7])

In [ ]:
X = np.array([[1,2,3],
              [3,4,5]])
X

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
print(np.sum(X,axis=0))
print(np.sum(X,axis=1))

[4 6 8]
[ 6 12]


In [ ]:
np.mean(X,axis=-1) #제일 뒷축의 mean을 구한다

array([2., 4.])

In [61]:
X = np.array([1,2,3])
X

array([1, 2, 3])

### Broadcasting

In [62]:
X+1 #broadcasting 방법이 적용돼서 모든 원소에 1이 더해지는 것이다. X+1 -> X+[1,1,1]

array([2, 3, 4])

In [63]:
#broadcasting 되는 기준: 늘렸을 때 서로 모양이 맞게될 경우 broadcasting이 된다.
X = np.arange(3).reshape(3,1)
X

array([[0],
       [1],
       [2]])

In [64]:
Y = np.arange(3)
Y

array([0, 1, 2])

In [65]:
X+Y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [66]:
X = np.array([1,'2',3])
X

array(['1', '2', '3'], dtype='<U11')

In [67]:
X.astype(np.int32)  #대량의 파일을 받았을 때 메모리가 감당이 안되는 경우 메모리를 줄이는 작업하기 위해 간혹 쓰이는 함수

array([1, 2, 3])

# 난수 생성 함수

In [68]:
import numpy as np

### np.random.random()
- [0.0,1.0) 범위의 숫자가 나온다

In [73]:
np.random.random((2,2))

array([[0.56788673, 0.32753405],
       [0.60528255, 0.83041184]])