In [4]:
import numpy as np

np.__version__

'1.21.0'

In [6]:
john = [10,8,6,7]
x = np.array(john)

print(type(x))

<class 'numpy.ndarray'>


In [ ]:
# 리스트에 있는 모든 원소에 1씩 추가::for문 방식
john = [10,8,6,7]

x = []
for i in john:
    x.append(i+1)

x

[11, 9, 7, 8]

In [ ]:
# 리스트 내포 방식 (이 방법을 이용해보도록 하자 ***)
x = [c+1 for c in john]
x

[11, 9, 7, 8]

In [ ]:
# numpy array를 활용한 방식
john = np.array(john)
john

array([10,  8,  6,  7])

In [ ]:
john+1

array([11,  9,  7,  8])

# 다차원 배열

In [ ]:
score = [[1,2,3,4],
        [5,6,7,8]]
X = np.array(score)
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
X.shape

(2, 4)

In [ ]:
X.dtype

dtype('int32')

In [ ]:
y = np.array([1.,2.,3.,4.])
y.shape

(4,)

In [ ]:
type(y.shape)

tuple

In [ ]:
x = (4)
type(x)

int

In [ ]:
type((4,)),type((4))

(tuple, int)

In [ ]:
X = np.arange(9)
X

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
X.shape

(9,)

In [ ]:
y = X.reshape(3,3)
y.shape

(3, 3)

In [ ]:
X.reshape(-1,3,3)  #-1을 넣게되면 나머지는 알아서 처리해달라는 뜻이다. 원소가 9개에 3x3이므로 1x3x3으로 자동세팅됨.

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
X = np.arange(0,16)
X = X.reshape(4,4)
X = X.reshape(2,4,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [ ]:
X = np.array([1,2,3])
y = np.array([[1],[2],[3]])
X.shape, y.shape

((3,), (3, 1))

In [ ]:
y =  y.reshape(-1)
y

array([1, 2, 3])

In [ ]:
X = np.arange(0,16)
X = X.reshape(-1,4,2)
X

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

# 슬라이싱, 인덱싱

In [46]:
X = np.array([[4,5,6],[8,9,0]])
X

array([[4, 5, 6],
       [8, 9, 0]])

### Fancy Indexing

In [47]:
X[0,[1,2]]

array([5, 6])

### Slicing

In [48]:
X[0,1:]

array([5, 6])

### Boolean Indexing

In [43]:
X = np.array([c for c in range(1,6)]) #[1,2,3,4,5]
idx = [False,True,False,True,False,]
X[idx]

array([2, 4])

In [ ]:
X = np.array([1,5,3,7,6])
X>6

array([False, False, False,  True, False])

In [ ]:
X[X>6]

array([7])

In [ ]:
X = np.array([[1,2,3],
              [3,4,5]])
X

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
print(np.sum(X,axis=0))
print(np.sum(X,axis=1))

[4 6 8]
[ 6 12]


In [ ]:
np.mean(X,axis=-1) #제일 뒷축의 mean을 구한다

array([2., 4.])

In [61]:
X = np.array([1,2,3])
X

array([1, 2, 3])

### Broadcasting

In [62]:
X+1 #broadcasting 방법이 적용돼서 모든 원소에 1이 더해지는 것이다. X+1 -> X+[1,1,1]

array([2, 3, 4])

In [63]:
#broadcasting 되는 기준: 늘렸을 때 서로 모양이 맞게될 경우 broadcasting이 된다.
X = np.arange(3).reshape(3,1)
X

array([[0],
       [1],
       [2]])

In [64]:
Y = np.arange(3)
Y

array([0, 1, 2])

In [65]:
X+Y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [66]:
X = np.array([1,'2',3])
X

array(['1', '2', '3'], dtype='<U11')

In [67]:
X.astype(np.int32)  #대량의 파일을 받았을 때 메모리가 감당이 안되는 경우 메모리를 줄이는 작업하기 위해 간혹 쓰이는 함수

array([1, 2, 3])

# 난수 생성 함수

In [2]:
import numpy as np

### np.random.random()
- [0.0,1.0) 범위의 숫자가 나온다

In [73]:
np.random.random((2,2))

array([[0.56788673, 0.32753405],
       [0.60528255, 0.83041184]])

### rand() 0~1의 균일분포

In [76]:
np.random.rand(2,2)

array([[0.64780712, 0.49449649],
       [0.33475496, 0.54755925]])

#### 정규분포 추출 randn()

In [78]:
np.random.randn(3,2)

array([[ 0.25773285,  0.54630951],
       [-1.88836306,  1.5672819 ],
       [-1.36421516, -1.59307208]])

### randint()

In [83]:
np.random.randint(0,6,(3,2))

array([[5, 1],
       [0, 4],
       [1, 2]])

### seed()

In [85]:
np.random.seed(2022)
np.random.randn(3)

array([-0.0005279 , -0.27490142, -0.13928556])

In [3]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])

In [4]:
x+y

array([[ 6,  8],
       [10, 12]])

In [9]:
print(np.add(x,y))
print(np.subtract(x,y))
print(np.multiply(x,y))
print(np.divide(x,y))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [13]:
np.dot(x,y)
np.matmul(x,y) #matrix multiply 라는 뜻

#둘은 어찌보면 같아보이지만 차원이 달라지면 결과가 달라진다

array([[19, 22],
       [43, 50]])

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])

np.matmul(x,y)

32

In [15]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])
np.matmul(x,y)

array([[19, 22],
       [43, 50]])

### np.argmax() n축을 중심으로 최대값의 index를 구하는 함수

In [21]:
x = np.random.randn(5,4)
x

array([[-0.03077231,  1.18238614,  1.23689095,  0.50312536],
       [ 1.12590772, -0.34199732, -0.12470786,  1.48867008],
       [-0.95158855, -1.9025208 ,  0.14825634, -0.76280314],
       [ 0.09903676,  2.04650569, -0.60328592, -2.36709731],
       [-0.72543171, -2.28013288,  0.09856831, -0.1412175 ]])

In [23]:
print(np.argmax(x,axis=0)) #열방향
print(np.argmax(x,axis=1)) #행방향

[1 3 0 1]
[2 3 2 1 2]


### savez() 파일 저장함수

In [26]:
x = np.random.randn(5,4)
y = np.random.randn(3,3)
x

array([[ 0.20567679,  0.03133624, -0.63384248, -0.29895264],
       [-0.89821525, -0.03415793,  0.94449403,  0.06669507],
       [ 0.30186268,  0.59935703, -0.40274768, -1.36339442],
       [-0.84809601,  0.36017983, -0.06941178, -0.72486292],
       [ 1.16374356,  0.4107561 ,  1.21750624, -1.4377163 ]])

In [27]:
y

array([[-1.68914283, -0.60093871, -1.54576007],
       [-1.61863678,  0.0866914 ,  0.43233746],
       [ 0.64923703, -0.8926852 ,  0.27491865]])

In [ ]:
np.savez('mydata.npz',xvar = x, yvar=y, 